development:
  adapter: postgresql
  database: mydb
  username:  # replace this with your own user name
  password:  # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: 
  password: 


