development:
  adapter: postgresql
  database: mydb
  username: dconlin # replace this with your own user name
  password: SuNFL0Wer # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: 5
  username: dconlin
  password: SuNFL0Wer


