require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForeignObjectsController do

  # This should return the minimal set of attributes required to create a valid
  # ForeignObject. As you add validations to ForeignObject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForeignObjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all foreign_objects as @foreign_objects" do
      foreign_object = ForeignObject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:foreign_objects).should eq([foreign_object])
    end
  end

  describe "GET show" do
    it "assigns the requested foreign_object as @foreign_object" do
      foreign_object = ForeignObject.create! valid_attributes
      get :show, {:id => foreign_object.to_param}, valid_session
      assigns(:foreign_object).should eq(foreign_object)
    end
  end

  describe "GET new" do
    it "assigns a new foreign_object as @foreign_object" do
      get :new, {}, valid_session
      assigns(:foreign_object).should be_a_new(ForeignObject)
    end
  end

  describe "GET edit" do
    it "assigns the requested foreign_object as @foreign_object" do
      foreign_object = ForeignObject.create! valid_attributes
      get :edit, {:id => foreign_object.to_param}, valid_session
      assigns(:foreign_object).should eq(foreign_object)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForeignObject" do
        expect {
          post :create, {:foreign_object => valid_attributes}, valid_session
        }.to change(ForeignObject, :count).by(1)
      end

      it "assigns a newly created foreign_object as @foreign_object" do
        post :create, {:foreign_object => valid_attributes}, valid_session
        assigns(:foreign_object).should be_a(ForeignObject)
        assigns(:foreign_object).should be_persisted
      end

      it "redirects to the created foreign_object" do
        post :create, {:foreign_object => valid_attributes}, valid_session
        response.should redirect_to(ForeignObject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved foreign_object as @foreign_object" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignObject.any_instance.stub(:save).and_return(false)
        post :create, {:foreign_object => {}}, valid_session
        assigns(:foreign_object).should be_a_new(ForeignObject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignObject.any_instance.stub(:save).and_return(false)
        post :create, {:foreign_object => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested foreign_object" do
        foreign_object = ForeignObject.create! valid_attributes
        # Assuming there are no other foreign_objects in the database, this
        # specifies that the ForeignObject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForeignObject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => foreign_object.to_param, :foreign_object => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested foreign_object as @foreign_object" do
        foreign_object = ForeignObject.create! valid_attributes
        put :update, {:id => foreign_object.to_param, :foreign_object => valid_attributes}, valid_session
        assigns(:foreign_object).should eq(foreign_object)
      end

      it "redirects to the foreign_object" do
        foreign_object = ForeignObject.create! valid_attributes
        put :update, {:id => foreign_object.to_param, :foreign_object => valid_attributes}, valid_session
        response.should redirect_to(foreign_object)
      end
    end

    describe "with invalid params" do
      it "assigns the foreign_object as @foreign_object" do
        foreign_object = ForeignObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => foreign_object.to_param, :foreign_object => {}}, valid_session
        assigns(:foreign_object).should eq(foreign_object)
      end

      it "re-renders the 'edit' template" do
        foreign_object = ForeignObject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForeignObject.any_instance.stub(:save).and_return(false)
        put :update, {:id => foreign_object.to_param, :foreign_object => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested foreign_object" do
      foreign_object = ForeignObject.create! valid_attributes
      expect {
        delete :destroy, {:id => foreign_object.to_param}, valid_session
      }.to change(ForeignObject, :count).by(-1)
    end

    it "redirects to the foreign_objects list" do
      foreign_object = ForeignObject.create! valid_attributes
      delete :destroy, {:id => foreign_object.to_param}, valid_session
      response.should redirect_to(foreign_objects_url)
    end
  end

end
