require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NonconformancesController do

  # This should return the minimal set of attributes required to create a valid
  # Nonconformance. As you add validations to Nonconformance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NonconformancesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nonconformances as @nonconformances" do
      nonconformance = Nonconformance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nonconformances).should eq([nonconformance])
    end
  end

  describe "GET show" do
    it "assigns the requested nonconformance as @nonconformance" do
      nonconformance = Nonconformance.create! valid_attributes
      get :show, {:id => nonconformance.to_param}, valid_session
      assigns(:nonconformance).should eq(nonconformance)
    end
  end

  describe "GET new" do
    it "assigns a new nonconformance as @nonconformance" do
      get :new, {}, valid_session
      assigns(:nonconformance).should be_a_new(Nonconformance)
    end
  end

  describe "GET edit" do
    it "assigns the requested nonconformance as @nonconformance" do
      nonconformance = Nonconformance.create! valid_attributes
      get :edit, {:id => nonconformance.to_param}, valid_session
      assigns(:nonconformance).should eq(nonconformance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nonconformance" do
        expect {
          post :create, {:nonconformance => valid_attributes}, valid_session
        }.to change(Nonconformance, :count).by(1)
      end

      it "assigns a newly created nonconformance as @nonconformance" do
        post :create, {:nonconformance => valid_attributes}, valid_session
        assigns(:nonconformance).should be_a(Nonconformance)
        assigns(:nonconformance).should be_persisted
      end

      it "redirects to the created nonconformance" do
        post :create, {:nonconformance => valid_attributes}, valid_session
        response.should redirect_to(Nonconformance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nonconformance as @nonconformance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nonconformance.any_instance.stub(:save).and_return(false)
        post :create, {:nonconformance => {}}, valid_session
        assigns(:nonconformance).should be_a_new(Nonconformance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nonconformance.any_instance.stub(:save).and_return(false)
        post :create, {:nonconformance => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nonconformance" do
        nonconformance = Nonconformance.create! valid_attributes
        # Assuming there are no other nonconformances in the database, this
        # specifies that the Nonconformance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nonconformance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nonconformance.to_param, :nonconformance => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nonconformance as @nonconformance" do
        nonconformance = Nonconformance.create! valid_attributes
        put :update, {:id => nonconformance.to_param, :nonconformance => valid_attributes}, valid_session
        assigns(:nonconformance).should eq(nonconformance)
      end

      it "redirects to the nonconformance" do
        nonconformance = Nonconformance.create! valid_attributes
        put :update, {:id => nonconformance.to_param, :nonconformance => valid_attributes}, valid_session
        response.should redirect_to(nonconformance)
      end
    end

    describe "with invalid params" do
      it "assigns the nonconformance as @nonconformance" do
        nonconformance = Nonconformance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nonconformance.any_instance.stub(:save).and_return(false)
        put :update, {:id => nonconformance.to_param, :nonconformance => {}}, valid_session
        assigns(:nonconformance).should eq(nonconformance)
      end

      it "re-renders the 'edit' template" do
        nonconformance = Nonconformance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nonconformance.any_instance.stub(:save).and_return(false)
        put :update, {:id => nonconformance.to_param, :nonconformance => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nonconformance" do
      nonconformance = Nonconformance.create! valid_attributes
      expect {
        delete :destroy, {:id => nonconformance.to_param}, valid_session
      }.to change(Nonconformance, :count).by(-1)
    end

    it "redirects to the nonconformances list" do
      nonconformance = Nonconformance.create! valid_attributes
      delete :destroy, {:id => nonconformance.to_param}, valid_session
      response.should redirect_to(nonconformances_url)
    end
  end

end
