require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WasteCapturesController do

  # This should return the minimal set of attributes required to create a valid
  # WasteCapture. As you add validations to WasteCapture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WasteCapturesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all waste_captures as @waste_captures" do
      waste_capture = WasteCapture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:waste_captures).should eq([waste_capture])
    end
  end

  describe "GET show" do
    it "assigns the requested waste_capture as @waste_capture" do
      waste_capture = WasteCapture.create! valid_attributes
      get :show, {:id => waste_capture.to_param}, valid_session
      assigns(:waste_capture).should eq(waste_capture)
    end
  end

  describe "GET new" do
    it "assigns a new waste_capture as @waste_capture" do
      get :new, {}, valid_session
      assigns(:waste_capture).should be_a_new(WasteCapture)
    end
  end

  describe "GET edit" do
    it "assigns the requested waste_capture as @waste_capture" do
      waste_capture = WasteCapture.create! valid_attributes
      get :edit, {:id => waste_capture.to_param}, valid_session
      assigns(:waste_capture).should eq(waste_capture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WasteCapture" do
        expect {
          post :create, {:waste_capture => valid_attributes}, valid_session
        }.to change(WasteCapture, :count).by(1)
      end

      it "assigns a newly created waste_capture as @waste_capture" do
        post :create, {:waste_capture => valid_attributes}, valid_session
        assigns(:waste_capture).should be_a(WasteCapture)
        assigns(:waste_capture).should be_persisted
      end

      it "redirects to the created waste_capture" do
        post :create, {:waste_capture => valid_attributes}, valid_session
        response.should redirect_to(WasteCapture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved waste_capture as @waste_capture" do
        # Trigger the behavior that occurs when invalid params are submitted
        WasteCapture.any_instance.stub(:save).and_return(false)
        post :create, {:waste_capture => {}}, valid_session
        assigns(:waste_capture).should be_a_new(WasteCapture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WasteCapture.any_instance.stub(:save).and_return(false)
        post :create, {:waste_capture => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested waste_capture" do
        waste_capture = WasteCapture.create! valid_attributes
        # Assuming there are no other waste_captures in the database, this
        # specifies that the WasteCapture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WasteCapture.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => waste_capture.to_param, :waste_capture => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested waste_capture as @waste_capture" do
        waste_capture = WasteCapture.create! valid_attributes
        put :update, {:id => waste_capture.to_param, :waste_capture => valid_attributes}, valid_session
        assigns(:waste_capture).should eq(waste_capture)
      end

      it "redirects to the waste_capture" do
        waste_capture = WasteCapture.create! valid_attributes
        put :update, {:id => waste_capture.to_param, :waste_capture => valid_attributes}, valid_session
        response.should redirect_to(waste_capture)
      end
    end

    describe "with invalid params" do
      it "assigns the waste_capture as @waste_capture" do
        waste_capture = WasteCapture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WasteCapture.any_instance.stub(:save).and_return(false)
        put :update, {:id => waste_capture.to_param, :waste_capture => {}}, valid_session
        assigns(:waste_capture).should eq(waste_capture)
      end

      it "re-renders the 'edit' template" do
        waste_capture = WasteCapture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WasteCapture.any_instance.stub(:save).and_return(false)
        put :update, {:id => waste_capture.to_param, :waste_capture => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested waste_capture" do
      waste_capture = WasteCapture.create! valid_attributes
      expect {
        delete :destroy, {:id => waste_capture.to_param}, valid_session
      }.to change(WasteCapture, :count).by(-1)
    end

    it "redirects to the waste_captures list" do
      waste_capture = WasteCapture.create! valid_attributes
      delete :destroy, {:id => waste_capture.to_param}, valid_session
      response.should redirect_to(waste_captures_url)
    end
  end

end
